import type { ActionEffectId } from "../../shared/navigation-tree";

export type ActionEffect = {
  id: ActionEffectId;
};

export const ACTION_EFFECTS = {
  "go-to-previous-tab": true,
  "go-to-parent-tab": true,
  "go-back-in-tab": true,
  "go-forward-in-tab": true,
  "go-to-prev-vertical-tab": true,
  "go-to-next-vertical-tab": true,
  "move-tab-to-start": true,
  "move-tab-to-end": true,
  "scroll-to-current-tab": true,
  "unload-tab": true,
  "open-options": true,
  "go-to-next-workspace": true,
  "go-to-prev-workspace": true,
  "workspace-edit-theme": true,
  "workspace-create": true,
  "workspace-delete": true,
  "workspace-unload": true,
  "workspace-unload-other-spaces": true,
  "toggle-pin-tab": true,
  "copy-url-markdown": true,
  "restore-last-closed-tab": true,
  "reload-tab": true,
  "reload-skip-cache": true,
  "duplicate-tab": true,
  "toggle-reader-mode": true,
  "view-page-source": true,
  "view-page-info": true,
  "toggle-mute": true,
  "reset-pinned-tab": true,
  "replace-pinned-url": true,
  "add-to-essentials": true,
  "take-screenshot": true,
  "toggle-pip": true,
  "toggle-fullscreen": true,
  "mark-tabs-new": true,
  "unvisited-newest": true,
  "unvisited-oldest": true,
  "toggle-devtools": true,
  "toggle-browser-toolbox": true,
  "open-downloads": true,
  "open-addons": true,
  "open-firefox-view": true,
  "copy-url": true,
  "replay-last-chord": true,
  "split-new": true,
  "split-close": true,
  "split-horizontal": true,
  "split-vertical": true,
  "sort-tabs-recent-desc": true,
  "sort-tabs-recent-asc": true,
  "sort-tabs-domain-alpha": true,
  "sort-tabs-domain-pop": true,
  "sort-tabs-age-asc": true,
  "sort-tabs-age-desc": true,
  "sort-tabs-inactive-bottom": true,
  "sort-tabs-most-visited": true,
  "sort-tabs-group-dups": true,
  "close-and-select-default": true,
  "close-and-select-previous": true,
  "close-and-select-parent": true,
  "close-and-select-next-sibling": true,
  "close-and-select-prev-sibling": true,
  "close-and-select-next-vertical": true,
  "close-and-select-prev-vertical": true,
  "close-and-select-unvisited-newest": true,
  "close-and-select-unvisited-oldest": true,
} as const satisfies Record<ActionEffectId, true>;

export function isActionEffectId(id: string): id is ActionEffectId {
  return id in ACTION_EFFECTS;
}
